import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-3xl mx-auto my-4`}
      >
          <Navbar />
          <div>{children}</div>
          <footer className="absolute bottom-0 pt-6 pb-4 text-center text-sm text-gray-300">
            Created by{" "}
            <a
              href="https://instagram.com/sbek22"
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-primary hover:underline text-blue-400"
            >
              Bek Slambek
            </a>
          </footer>
      </body>
    </html>
  );
}
